### ISSUE TITLE
Posts - Add page number and shelf type fields 

### ISSUE THREAD

**Issue by Vnovnick** [Vnovnick/jourbooks#4]
# What
This will allow the user to input the page number they are at with a given post to have a better sense of when the post was written. Having the shelf type will also give a better sense of progress. Both fields will be optional

# TODOs
 - Add fields to "posts" table and make necessary api adjustments
 - Add inputs for the posts on the frontend

**Comment by Propnick** [comment]
2/21 update - Added fields in the DB and post api request. Need to add page number and shelf type fields to the patch request and edit form on the frontend.

**Comment by Vnovnick** [comment]
[Completed](https://github.com/Vnovnick/jourbooks/commit/6dc9be2f20e3f451869ed59e7caf4758b125412e) with some additional changes to fix review data invalidation.
